/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class andro_jf_jni_NativeCodeInterface */

#ifndef _Included_andro_jf_jni_NativeCodeInterface
#define _Included_andro_jf_jni_NativeCodeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     andro_jf_jni_NativeCodeInterface
 * Method:    calcul1
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_andro_jf_jni_NativeCodeInterface_calcul1
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
